import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  interviewSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ]
}

export default sidebars
