export default {
  Done: [
    'p0-execute-context',
    'p0-promise',
    'p0-instanceof',
    'p0-object',
    'p0-type-check',
    'p0-prototype-chain',
    'p0-new',
    'p0-operator-equal',
    'p0-types',
    'p0-ieee754',
    'p0-primitive-reference',
    'p0-react-lifecycle',
    'p0-controlled-uncontrolled-component',
    'p0-hoc',
    'p0-react-component-communication',
    'p0-react-key',
    'p0-createPortal',
    'p1-setState',
    'p0-react-react-dom',
    'p0-react-element-component',
    'p0-engineering',

    //  vue
    'p0-vue-component',
    'p0-component-type',
    'p0-vue-lifecycle',
    'p0-component-options',
    'p0-composition-api'
  ],
  SubjectPriority: [
    'vue',
    'react',
    'js',
    'network',
    'html',
    'css',
    'engineering',
    'algorithm',
    'typescript',
    'operate-system',
    'node',
    'paradigm',
    'coding',
    'interview',
    'hybird'
  ],
  DeadLine: '2025-05-31 23:59:59'
}
