export default {
  Done: [
    // js
    'p0-check-property',
    'p0-async-promise',
    'p0-throttle',
    'p0-debounce',
    'p0-hidden-class',
    'p0-memory',
    'P0-jit',
    'p0-v8',
    'p0-explain-compile',
    'p0-async-programing',
    'p0-cps',
    'p0-let-const-var',
    'p0-call-apply-bind',
    'p0-arrow-function',
    'p0-create-function',
    'p0-constructor-call',
    'p0-this',
    'p0-closure',
    'p0-scope',
    'p0-execute-context',
    'p0-promise',
    'p0-instanceof',
    'p0-object',
    'p0-type-check',
    'p0-prototype-chain',
    'p0-new',
    'p0-operator-equal',
    'p0-types',
    'p0-ieee754',
    'p0-primitive-reference',
    'p0-react-lifecycle',
    'p0-controlled-uncontrolled-component',
    'p0-hoc',
    'p0-react-component-communication',
    'p0-react-key',
    'p0-createPortal',
    'p1-setState',
    'p0-react-react-dom',
    'p0-react-element-component',
    'p0-engineering',

    //  vue
    'p0-vue-component',
    'p0-component-type',
    'p0-vue-lifecycle',
    'p0-component-options',
    'p0-composition-api',

    // paradigm function
    'p0-effecitve'
  ],
  SubjectPriority: [
    'js',
    'html',
    'vue',
    'react',
    'network',
    'css',
    'engineering',
    'algorithm',
    'typescript',
    'os',
    'system-design',
    'nodejs',
    'paradigm',
    'interview',
    'rn',
    'miniprogram'
  ],
  DeadLine: '2025-07-31 23:59:59'
}
